### PR TITLE
Effect size density plots and expected distance values

### PR DESCRIPTION
**Pull request by brandonlieng**
- Functions to allow for the generation of effect size density plots added

- Functions to calculate expected distance values added

- Methods changed -- getMonteCarloSample() replaces getMonteCarloReplicate() and returns the matrix with all instances for a sample (matrix is D features by x mc.samples); getMonteInstance() returns the n-th instance matrix (matrix is n samples and D features)

### CODE REVIEW

**Comment by brandonlieng** [comment]
@ggloor, b791a4e and f5d7edf were caught when using the `aldex.plot()` function. A set of erroneous method calls in `clr_effect.r` resulted in miscalculations of effect sizes.

**Comment by ggloor** [comment]
any reason you changed that function? it may break stuff that others depend on

**Comment by brandonlieng** [comment]
I haven't added new features that depend on the `expectedDistance()` function yet-- this was one of the new functions implemented back in May. I figured returning a `dist`-class made sense since base `dist()` does as well.

**Comment by brandonlieng** [comment]
As per in-person discussion:

* Although changing the method names would not affect anything internal to `ALDEx2` since calls were also updated, other packages that rely on `ALDEx2` may be unexpectedly affected. This will be undone and a new method will be added with a new name instead.

* IQLR and LVHA will be checked upon output for having more than 5 members rather than checking the input.

Closing this pull request until above changes are made.

**Comment by brandonlieng** [comment]
- Method names changed back (undoing c881904)

- IQLR/LVHA functions that return feature sets now have a check to stop if five or fewer members are present in the invariant set: `if(length(invariant.set) <= 5) stop("Five or fewer members in intersecting feature set")`
    - Undoing 37fba8, where number of input features were checked instead

**Comment by dgiguer** [comment]
@ggloor can this request be pulled in and propagated with a version bump? would be great to have omicplotR get the plotting feature in the new Bioc release!

**Pull request merged**
